services:
  app:
    build: .
    volumes:
      - .:/code
    container_name: app
  exchange-api:
    image: mockserver/mockserver
    ports:
    - 1080:1080
    volumes:
      - ./docker/initializerJson.json:/config/initializerJson.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json